# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm -v
    - run: node -v
    - run: npm install
    - run: PORT=$PORT DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PW=$DB_PW JWT_SECRET=$JWT_SECRET USER_IMAGE_DIRECTORY=$USER_IMAGE_DIRECTORY EVENT_IMAGE_DIRECTORY=$EVENT_IMAGE_DIRECTORY ASSETS_DIRECTORY=$ASSETS_DIRECTORY pm2 restart AltruiztAPI --update-env
      env:
        PORT: ${{ secrets.PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PW: ${{ secrets.DB_PW }}
        DB_USER: ${{ secrets.DB_USER }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        USER_IMAGE_DIRECTORY: ${{ secrets.USER_IMAGE_DIRECTORY }}
        EVENT_IMAGE_DIRECTORY: ${{ secrets.EVENT_IMAGE_DIRECTORY }}
        ASSETS_DIRECTORY: ${{ secrets.ASSETS_DIRECTORY }}

        